name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install CI dependencies
      run: npm ci
    - name: Setup Date field
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW # Gives "2022-12-11T01:42:20"
    - name: Install Playwright Browsers 3
      run: npx playwright install --with-deps
    - name: Run Playwright all tests inside test DIR
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ env.NOW }}
        path: playwright-report/
        retention-days: 30
